version: '3'

services:
  db:
    image: postgres:latest

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blogdb

    ports:
      - '5555:5432'

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 10s
      retries: 5

  blog:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '4999:4999'

    depends_on:
      db:
        condition: service_healthy

    links:
      - db

    restart: always
